# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: nerai
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: app-nutri
# "service" is the name of this project. This will also be added to your AWS resource names.
service: app-api

plugins:
  - serverless-offline

provider:
  name: aws
  region: us-east-1
  runtime: nodejs22.x
  architecture: arm64
  environment:
    DATABASE_URL: ${env:DATABASE_URL}
    JWT_SECRET: ${env:JWT_SECRET}

build:
  esbuild:
    minify: true
    sourcemap: false

package:
  individually: true

functions:
  signin:
    handler: src/fuctions/signin.handler
    events:
      - httpApi:
          path: /signin
          method: post

  signup:
    handler: src/fuctions/signup.handler
    events:
      - httpApi:
          path: /signup
          method: post

  me:
    handler: src/fuctions/me.handler
    events:
      - httpApi:
          path: /me
          method: get

  createMeal:
    handler: src/fuctions/createMeal.handler
    events:
      - httpApi:
          path: /meals
          method: post

  listMeals:
    handler: src/fuctions/listMeals.handler
    events:
      - httpApi:
          path: /meals
          method: get 

  getMealById:
    handler: src/fuctions/getMealById.handler
    events:
      - httpApi:
          path: /meals/{mealId}
          method: get

resources:
  Resources:
    uploadBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: nerai-appnutri-upload